export const predictTests = (symptoms) => {

    const symptomTestMap = {
        "fever": ["Complete Blood Count (CBC)", "Malaria Test", "Typhoid Test", "Dengue Test", "Blood Culture"],
        "cough": ["Chest X-ray", "COVID-19 PCR Test", "Sputum Culture", "Pulmonary Function Test", "Tuberculosis (TB) Test"],
        "headache": ["MRI Brain", "CT Scan Brain", "Electroencephalogram (EEG)", "Lumbar Puncture"],
        "stomach pain": ["Abdominal Ultrasound", "Liver Function Test", "Endoscopy", "H. Pylori Test", "Stool Test"],
        "fatigue": ["Thyroid Function Test", "Vitamin Deficiency Test", "Iron Studies", "Diabetes Test", "Cortisol Test"],
        "nausea": ["Liver Function Test", "H. Pylori Test", "Pregnancy Test", "Kidney Function Test", "Electrolyte Panel"],
        "vomiting": ["Electrolyte Panel", "Abdominal Ultrasound", "Food Poisoning Test", "Liver Function Test", "Pancreatic Enzyme Test"],
        "diarrhea": ["Stool Test", "Electrolyte Panel", "Celiac Disease Test", "Salmonella Test", "Rotavirus Test"],
        "constipation": ["Thyroid Test", "Colonoscopy", "Fecal Occult Blood Test", "Magnesium Level Test", "X-ray Abdomen"],
        "chest pain": ["ECG", "Troponin Test", "Echocardiogram", "CT Coronary Angiography", "Lipid Profile"],
        "shortness of breath": ["Pulmonary Function Test", "ECG", "D-dimer Test", "Arterial Blood Gas (ABG)", "Chest X-ray"],
        "high blood pressure": ["Lipid Profile", "Kidney Function Test", "Electrocardiogram (ECG)", "24-Hour Blood Pressure Monitor"],
        "low blood pressure": ["Electrolyte Panel", "Cortisol Test", "ECG", "Complete Blood Count (CBC)"],
        "palpitations": ["Holter Monitor Test", "Thyroid Test", "ECG", "Electrolyte Panel"],
        "dizziness": ["MRI Brain", "CT Scan Brain", "Blood Pressure Test", "Vitamin B12 Test", "Hearing Test"],
        "ear pain": ["Otoscopy", "Ear Swab Culture", "Tympanometry", "Audiometry"],
        "hearing loss": ["Audiometry", "Otoscopy", "MRI Brain"],
        "sore throat": ["Throat Swab Culture", "Strep Test", "Monospot Test"],
        "runny nose": ["Allergy Test", "Nasal Swab PCR", "Sinus X-ray"],
        "sinus pain": ["Sinus X-ray", "CT Sinus", "Allergy Test"],
        "skin rash": ["Allergy Panel", "Skin Biopsy", "Autoimmune Panel"],
        "itching": ["Allergy Test", "Eosinophil Count", "Skin Patch Test"],
        "joint pain": ["Rheumatoid Factor Test", "Anti-CCP Antibody Test", "Uric Acid Test"],
        "muscle pain": ["CK (Creatine Kinase) Test", "Magnesium Level Test"],
        "weakness": ["Vitamin D Test", "Vitamin B12 Test", "Thyroid Function Test"],
        "weight loss": ["Thyroid Function Test", "Diabetes Test", "Cancer Screening"],
        "weight gain": ["Thyroid Function Test", "Cortisol Test", "Lipid Profile"],
        "excessive thirst": ["Diabetes Test", "Kidney Function Test"],
        "excessive urination": ["Diabetes Test", "Urinalysis", "Kidney Function Test"],
        "burning sensation while urinating": ["Urinalysis", "Urine Culture"],
        "blood in urine": ["Urine Culture", "Kidney Function Test", "CT Urogram"],
        "back pain": ["Spine MRI", "X-ray Spine", "Vitamin D Test"],
        "leg swelling": ["D-dimer Test", "Doppler Ultrasound"],
        "anemia": ["Complete Blood Count (CBC)", "Iron Panel", "Folate & Vitamin B12 Test"],
        "liver problems": ["Liver Function Test", "Hepatitis Panel", "Abdominal Ultrasound"],
        "kidney problems": ["Kidney Function Test", "Urine Test", "Electrolyte Panel"],
        "diabetes symptoms": ["Fasting Blood Sugar", "HbA1c Test", "Insulin Test"],
        "thyroid issues": ["TSH, T3, T4 Test"],
        "cancer symptoms": ["Tumor Markers Test", "Biopsy", "CT Scan"],
        "hormonal imbalance": ["Cortisol Test", "Testosterone/Estrogen Levels", "Thyroid Panel"],
        "memory loss": ["MRI Brain", "Vitamin B12 Test", "Cognitive Function Test"],
        "blurred vision": ["Eye Test", "Diabetes Test"],
        "red eyes": ["Eye Culture", "Allergy Test"],
        "night blindness": ["Vitamin A Test"],
        "dry skin": ["Vitamin Deficiency Test", "Thyroid Test"],
        "frequent infections": ["Complete Blood Count (CBC)", "Immunoglobulin Panel"],
        "hair loss": ["Thyroid Panel", "Iron Test", "Vitamin D Test"],
        "abdominal bloating": ["H. Pylori Test", "Food Allergy Test"],
        "acid reflux": ["Endoscopy", "H. Pylori Test"],
        "bruising easily": ["Platelet Count", "Coagulation Profile"],
        "frequent headaches": ["CT Brain", "MRI Brain", "Migraine Panel"],
        "menstrual irregularities": ["Hormone Panel", "Pelvic Ultrasound"],
        "chronic pain": ["Pain Management Panel", "Autoimmune Panel"],
        "cold hands and feet": ["Circulation Test", "Thyroid Panel"],
        "sleep disturbances": ["Polysomnography", "Cortisol Test"],
        "depression": ["Cortisol Test", "Vitamin D & B12 Test"],
        "anxiety": ["Thyroid Panel", "Cortisol Test"],
        "panic attacks": ["ECG", "Electrolyte Panel"],
        "difficulty swallowing": ["Barium Swallow Test", "Endoscopy"],
        "excessive sweating": ["Thyroid Panel", "Cortisol Test"],
        "hormonal acne": ["Testosterone Levels", "PCOS Panel"],
        "dark urine": ["Liver Function Test", "Kidney Function Test"],
        "swollen glands": ["Complete Blood Count (CBC)", "Lymph Node Biopsy"],
        "chronic cough": ["TB Test", "Chest X-ray"],
        "recurrent fever": ["Blood Culture", "Autoimmune Panel"],
        "stroke symptoms": ["Brain MRI", "CT Angiography"],
        "chronic fatigue": ["Thyroid Panel", "Cortisol Test", "Vitamin Panel"],
        "numbness in hands/feet": ["Nerve Conduction Study", "Blood Sugar Test"],
        "low libido": ["Testosterone Levels", "Estrogen Levels"],
        "irregular heartbeat": ["Holter Monitor", "Electrolyte Panel"],
        "poor appetite": ["Liver Function Test", "Thyroid Panel"],
        "chronic sinusitis": ["Sinus CT Scan", "Allergy Test"],
        "frequent nosebleeds": ["Platelet Count", "Coagulation Profile"],
        "fainting": ["Blood Pressure Test", "ECG", "Blood Sugar Test"]
     };

    let recommendedTests = new Set();
    symptoms.forEach(symptom => {
        if (symptomTestMap[symptom.toLowerCase()]) {
            symptomTestMap[symptom.toLowerCase()].forEach(test => recommendedTests.add(test));
        }
    });

    return recommendedTests.size ? Array.from(recommendedTests) : ["General Checkup"];
};
